backend:
  username: "admin"
  password: "0000"

  port: 8888

  jwt:
    secret: "work-tracker"
    expiresIn: 1h

  db:
    type: "bbolt"
    path: "./db/wt.db"

  frontendFilePath: "frontend"

logger:
  level: "info"
