services:
  wt:
    container_name: wt
    image: alonza0314/work-tracker:latest
    command: ./wt -c config.yaml
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - ./config.yaml:/wt/config.yaml
      - /var/lib/wt/db:/wt/db
